### ISSUE TITLE
github actionsのカスタムアクションの作り方メモ

### ISSUE THREAD

**Issue by Akira-Isegawa** [Akira-Isegawa/Akira-Isegawa.github.io#9]
# ToDo
- [x] 公式ドキュメントを確認
- [x] github actionsのローカルでの実行方法を確認
- [x] githubのpull requestのデータを取得する方法
- [x] secretの受け渡し方法
- [x] 外部サービスのデータの取得方法 → 通常のnode.jsの方法でアクセス可能
- [x] pull requestに結果を出力する方法

# 公式ドキュメントの情報
- カスタムアクションとは
  - https://docs.github.com/ja/actions/creating-actions/about-custom-actions
  - github actionsのアクションの内容をカスタマイズできる
  - marketplaceに公開することもできるし、privateリポジトリでも自分のカスタムアクションや自組織（organization）のカスタムアクションを利用することができる
- JavaScriptアクション
  - https://docs.github.com/ja/actions/creating-actions/creating-a-javascript-action
  - Dockerコンテナのアクションと、JavaScriptアクションがある
  - DockerコンテナのアクションよりもJavaScriptアクションの方が高速らしい（どのくらい？）
  - TypeScriptのテンプレートもある
    - https://github.com/actions/typescript-action

**Comment by Akira-Isegawa** [comment]
# github actionsをローカルで実行
参考資料
- https://github.com/nektos/act

インストール
```
brew install act
```

前提
- Docker Desktopを起動

実行可能なアクション一覧
```
act -l
```

pull request時のアクションを実行
```
act pull_request --container-architecture linux/amd64
```
- `--container-architecture linux/amd64` はM1 mac用の指定

特定のアクションを実行
```
act --container-architecture linux/amd64 -j test-action -W .github/workflows/ci.yml
```

**Comment by Akira-Isegawa** [comment]
# githubのpull requestのデータを取得する方法
## contextから取得
依存パッケージをインストール
```bash
npm install @actions/github
```

github.context.payload.pull_requestの中に、トリガー元となったpull requestのデータが入っている

```ts
import * as github from '@actions/github'

const pull_request = github.context.payload.pull_request
```

## octkitから取得
依存パッケージをインストール
```bash
npm install @octokit/core
```

octkitに適切な権限のGITHUB_TOKENを渡すと、githubからデータを取得できる。
下記はpull requestのdiffを取得するコードサンプル。

```ts

const token = process.env.GITHUB_TOKEN || ''
const octokit = github.getOctokit(token)

const { data: diffData } = await octokit.request({
  headers: {
    accept: 'application/vnd.github.diff'
  },
  method: 'GET',
  url: pullRequestUrl + '/files'
})

```

**Comment by Akira-Isegawa** [comment]
# pull requestに結果を出力する方法
## octkitでコメントを投稿する方法

## outputとして出力し、次のステップで汎用のgithub scriptでコメントを投稿する方法
output として出力

```ts
import * as core from '@actions/core'

core.setOutput('comments', commentText)
```

githubアクションの定義ファイル「action.yml」に出力を定義
```yml
outputs:
  comments:
    description: 'Comments to post'
```

github actionsのyaml
```yaml
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comments = `${{ steps.previous-action.outputs.comments }}`;
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: comments
            });
```

github scriptの使い方は下記参照
- https://github.com/actions/github-script
